#!/usr/bin/env bash
# This is a script displaying "Best School" 10 times using While loop
# On the 9th iteration, print "Hi" before "Best School"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
